/**
 * @fileoverview gRPC-Web generated client stub for invoicer
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.0
// source: invoicer.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.invoicer = require('./invoicer_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.invoicer.InvoicerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.invoicer.InvoicerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.invoicer.InvoiceRequest,
 *   !proto.invoicer.InvoiceResponse>}
 */
const methodDescriptor_Invoicer_GetInvoice = new grpc.web.MethodDescriptor(
  '/invoicer.Invoicer/GetInvoice',
  grpc.web.MethodType.UNARY,
  proto.invoicer.InvoiceRequest,
  proto.invoicer.InvoiceResponse,
  /**
   * @param {!proto.invoicer.InvoiceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.invoicer.InvoiceResponse.deserializeBinary
);


/**
 * @param {!proto.invoicer.InvoiceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.invoicer.InvoiceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.invoicer.InvoiceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.invoicer.InvoicerClient.prototype.getInvoice =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/invoicer.Invoicer/GetInvoice',
      request,
      metadata || {},
      methodDescriptor_Invoicer_GetInvoice,
      callback);
};


/**
 * @param {!proto.invoicer.InvoiceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.invoicer.InvoiceResponse>}
 *     Promise that resolves to the response
 */
proto.invoicer.InvoicerPromiseClient.prototype.getInvoice =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/invoicer.Invoicer/GetInvoice',
      request,
      metadata || {},
      methodDescriptor_Invoicer_GetInvoice);
};


module.exports = proto.invoicer;

